Repository FC-BE-ToyProject-Team8/TravelApp, pull requests merged in 2023-11, with the labels that each got.

#102 docs: PR 템플릿 작성
  pull_request_template.md
Labels: documentation

#105 PR 템플릿
  pull_request_template.md
Labels: documentation

#107 사용자 회원가입 & 로그인
  build.gradle
  src/main/java/kr/co/fastcampus/travel/common/exception/InvalidArgumentException.java
  src/main/java/kr/co/fastcampus/travel/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/travel/common/secure/config/SecurityConfig.java
  src/main/java/kr/co/fastcampus/travel/common/secure/domain/JwtProvider.java
  src/main/java/kr/co/fastcampus/travel/common/secure/domain/PrincipalDetails.java
  src/main/java/kr/co/fastcampus/travel/common/secure/domain/Token.java
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/MemberController.java
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/dto/MemberDtoMapper.java
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/dto/request/MemberSaveRequest.java
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/dto/response/MemberSaveResponse.java
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/request/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/response/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/travel/domain/member/repository/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/member/repository/MemberRepository.java
  src/main/java/kr/co/fastcampus/travel/domain/member/service/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/member/service/MemberService.java
  src/main/java/kr/co/fastcampus/travel/domain/member/service/dto/request/MemberSaveDto.java
  src/main/java/kr/co/fastcampus/travel/domain/member/service/dto/response/MemberDto.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/controller/SecurityController.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/controller/dto/SecurityDtoMapper.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/controller/dto/reqeust/LoginReqeust.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/controller/dto/response/LoginResponse.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/service/SecurityService.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/service/reqeust/LoginDto.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/service/response/TokenDto.java
  src/test/java/kr/co/fastcampus/travel/common/MemberTestUtils.java
  src/test/java/kr/co/fastcampus/travel/common/RestAssuredUtils.java
  src/test/java/kr/co/fastcampus/travel/common/TokenUtils.java
  src/test/java/kr/co/fastcampus/travel/common/TravelTestUtils.java
  src/test/java/kr/co/fastcampus/travel/domain/itinerary/controller/ItineraryControllerTest.java
  src/test/java/kr/co/fastcampus/travel/domain/member/controller/MemberControllerTest.java
  src/test/java/kr/co/fastcampus/travel/domain/member/service/MemberServiceTest.java
  src/test/java/kr/co/fastcampus/travel/domain/secure/controller/SecurityControllerTest.java
  src/test/java/kr/co/fastcampus/travel/domain/secure/service/SecurityServiceTest.java
  src/test/java/kr/co/fastcampus/travel/domain/trip/controller/TripControllerTest.java
Labels: enhancement

#104 SpringSecurity 세팅
  build.gradle
  src/main/java/kr/co/fastcampus/travel/common/exception/InvalidArgumentException.java
  src/main/java/kr/co/fastcampus/travel/common/exception/TokenExpireException.java
  src/main/java/kr/co/fastcampus/travel/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/travel/common/secure/config/SecurityConfig.java
  src/main/java/kr/co/fastcampus/travel/common/secure/config/SecurityConfigAdapter.java
  src/main/java/kr/co/fastcampus/travel/common/secure/config/SecurityFilter.java
  src/main/java/kr/co/fastcampus/travel/common/secure/config/handler/TokenAccessDeniedHandler.java
  src/main/java/kr/co/fastcampus/travel/common/secure/config/handler/TokenAuthenticationEntryPoint.java
  src/main/java/kr/co/fastcampus/travel/common/secure/domain/JwtProvider.java
  src/main/java/kr/co/fastcampus/travel/common/secure/domain/PrincipalDetails.java
  src/main/java/kr/co/fastcampus/travel/common/secure/domain/Token.java
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/MemberController.java
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/dto/MemberDtoMapper.java
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/dto/request/MemberSaveRequest.java
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/dto/response/MemberSaveResponse.java
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/request/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/member/controller/response/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/travel/domain/member/entity/RoleType.java
  src/main/java/kr/co/fastcampus/travel/domain/member/repository/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/member/repository/MemberRepository.java
  src/main/java/kr/co/fastcampus/travel/domain/member/service/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/member/service/MemberService.java
  src/main/java/kr/co/fastcampus/travel/domain/member/service/dto/request/MemberSaveDto.java
  src/main/java/kr/co/fastcampus/travel/domain/member/service/dto/response/MemberDto.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/controller/SecurityController.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/controller/dto/SecurityDtoMapper.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/controller/dto/request/LoginReqeust.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/controller/dto/response/LoginResponse.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/service/SecurityService.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/service/reqeust/LoginDto.java
  src/main/java/kr/co/fastcampus/travel/domain/secure/service/response/TokenDto.java
  src/main/resources/application.yml
  src/test/java/kr/co/fastcampus/travel/common/MemberTestUtils.java
  src/test/java/kr/co/fastcampus/travel/common/RestAssuredUtils.java
  src/test/java/kr/co/fastcampus/travel/common/TokenUtils.java
  src/test/java/kr/co/fastcampus/travel/common/TravelTestUtils.java
  src/test/java/kr/co/fastcampus/travel/domain/itinerary/controller/ItineraryControllerTest.java
  src/test/java/kr/co/fastcampus/travel/domain/member/controller/MemberControllerTest.java
  src/test/java/kr/co/fastcampus/travel/domain/member/service/MemberServiceTest.java
  src/test/java/kr/co/fastcampus/travel/domain/secure/controller/SecurityControllerTest.java
  src/test/java/kr/co/fastcampus/travel/domain/secure/service/SecurityServiceTest.java
  src/test/java/kr/co/fastcampus/travel/domain/trip/controller/TripControllerTest.java
  src/test/resources/application.yml
Labels: enhancement

#108 feature/99 멘토님 수정 사항 반영 및 스키마 문서 수정
  src/main/java/kr/co/fastcampus/travel/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/travel/domain/itinerary/entity/Stay.java
  src/main/resources/schema.sql
Labels: bug

#110 feature/100 사용자 닉네임으로 여행 찾기 기능 구현
  src/main/java/kr/co/fastcampus/travel/common/exception/DuplicatedLikeException.java
  src/main/java/kr/co/fastcampus/travel/common/exception/MemberNotFoundException.java
  src/main/java/kr/co/fastcampus/travel/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/travel/domain/like/controller/LikeController.java
  src/main/java/kr/co/fastcampus/travel/domain/like/controller/dto/LikeDtoMapper.java
  src/main/java/kr/co/fastcampus/travel/domain/like/controller/dto/request/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/like/controller/dto/request/LikeSaveRequest.java
  src/main/java/kr/co/fastcampus/travel/domain/like/controller/dto/response/.gitkeep
  src/main/java/kr/co/fastcampus/travel/domain/like/entity/Like.java
  src/main/java/kr/co/fastcampus/travel/domain/like/repository/LikeRepository.java
  src/main/java/kr/co/fastcampus/travel/domain/like/service/LikeService.java
  src/main/java/kr/co/fastcampus/travel/domain/like/service/dto/LikeSaveDto.java
  src/main/java/kr/co/fastcampus/travel/domain/member/repository/MemberRepository.java
  src/main/java/kr/co/fastcampus/travel/domain/member/service/MemberService.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/controller/TripController.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/entity/Trip.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/repository/TripRepository.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/service/TripService.java
  src/test/java/kr/co/fastcampus/travel/common/TravelTestUtils.java
  src/test/java/kr/co/fastcampus/travel/domain/trip/controller/TripControllerTest.java
  src/test/java/kr/co/fastcampus/travel/domain/trip/service/TripServiceTest.java
Labels: enhancement

#123 feature/64 좋아요 취소 구현
  src/main/java/kr/co/fastcampus/travel/common/exception/InvalidLikeCancelException.java
  src/main/java/kr/co/fastcampus/travel/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/travel/domain/like/controller/LikeController.java
  src/main/java/kr/co/fastcampus/travel/domain/like/repository/LikeRepository.java
  src/main/java/kr/co/fastcampus/travel/domain/like/service/LikeService.java
  src/main/java/kr/co/fastcampus/travel/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/controller/TripController.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/controller/dto/request/TripSaveRequest.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/controller/dto/response/TripResponse.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/controller/dto/response/TripSummaryResponse.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/entity/Trip.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/repository/TripRepository.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/service/TripService.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/service/dto/request/TripSaveDto.java
  src/test/java/kr/co/fastcampus/travel/common/RestAssuredUtils.java
  src/test/java/kr/co/fastcampus/travel/domain/like/controller/LikeControllerTest.java
  src/test/java/kr/co/fastcampus/travel/domain/like/service/LikeServiceTest.java
  src/test/java/kr/co/fastcampus/travel/domain/trip/service/TripServiceTest.java
Labels: enhancement

#121 h2 콘솔을 사용하기위한 설정 추가
  src/main/java/kr/co/fastcampus/travel/common/secure/config/SecurityConfig.java
Labels: bug

#139 Swagger 경로 Spring Security에 추가
  src/main/java/kr/co/fastcampus/travel/common/secure/config/SecurityConfig.java
Labels: bug

#144 내가 좋아요 누른 여행 목록
  src/main/java/kr/co/fastcampus/travel/domain/trip/controller/TripController.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/repository/TripRepository.java
  src/main/java/kr/co/fastcampus/travel/domain/trip/service/TripService.java
  src/test/java/kr/co/fastcampus/travel/common/MemberTestUtils.java
  src/test/java/kr/co/fastcampus/travel/common/RestAssuredUtils.java
  src/test/java/kr/co/fastcampus/travel/common/TokenUtils.java
  src/test/java/kr/co/fastcampus/travel/common/TravelTestUtils.java
  src/test/java/kr/co/fastcampus/travel/domain/member/controller/MemberControllerTest.java
  src/test/java/kr/co/fastcampus/travel/domain/trip/controller/TripControllerGetTripTest.java
  src/test/java/kr/co/fastcampus/travel/domain/trip/repository/TripRepositoryTest.java
  src/test/java/kr/co/fastcampus/travel/domain/trip/service/TripServiceTest.java
Labels: enhancement

#161 여정 포함 여행 조회 테스트 코드 작성
  src/main/java/kr/co/fastcampus/travel/common/secure/config/SecurityConfig.java
  src/test/java/kr/co/fastcampus/travel/common/RestAssuredUtils.java
  src/test/java/kr/co/fastcampus/travel/domain/trip/controller/TripControllerGetTripTest.java
Labels: enhancement

#165 여행 삭제 Security 기능 추가
  src/test/java/kr/co/fastcampus/travel/common/RestAssuredUtils.java
  src/test/java/kr/co/fastcampus/travel/domain/trip/controller/TripControllerGetTripTest.java
Labels: bug
